# Generated by Django 6.1 on 2026-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="appointment_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="appointment_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="interaction",
            name="appointment_purpose",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="interaction",
            name="appointment_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lingerie", "Lingerie"),
                    ("nightwear", "Nightwear"),
                    ("swimwear", "Swimwear"),
                    ("clothing", "Clothing"),
                    ("accessories", "Accessories"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_store",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="interaction",
            name="purchase_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
