# Generated by Django 6.1 on 2026-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="anniversary",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="birthday_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="birthday_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True, default="United Kingdom", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_country_code",
            field=models.CharField(blank=True, default="+44", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="mobile",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dr", "Dr."),
                    ("miss", "Miss."),
                    ("mr", "Mr."),
                    ("mrs", "Mrs."),
                    ("ms", "Ms."),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="spouse_birthday_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="spouse_birthday_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
