# Generated by Django 6.1 on 2026-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_customer_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
